export const MainRouteName = {
    LOGIN: 'Login',
    REGISTER: 'Register',
    FORGET_PASSWORD: 'Forget Password',
    CREATE_NEW_PASSWORD: 'Create New Password',
    CHANGE_PASSWORD: 'Change Password',
    HOME_NAVIGATOR: 'Home',
    LOGOUT: 'LOGOUT',
    HOME: 'Beranda',
    NOTIFICATION: 'Notification',
    ACCOUNT: 'Account',
    PROFILE_SETTING: 'Setting Profile',
    SELECT_LANGUAGE: 'Select Language',
    DETAIL_ARTICLE: 'Detail Article',
    ON_TESTING: 'On Testing',
    CUSTOM_PAGE: 'Custom Page',
    ADDRESS_SETTING: 'Setting Address',
    MEMBERSHIP: 'Membership',
    EMAIL_SENT: 'Email Sent',
    FRIEND_LIST: 'Daftar Teman',
    MAPS: 'Maps',
    TASK_LIST: 'Daftar Tugas',
    DETAIL_TASK: 'Detail',
    REMARK_TASK: 'Remark Task',
};
